blank_issues_enabled: false
contact_links:
  - name: 💬 Questions / Support
    url: https://github.com/airnub/next-supabase-i18n-a11y-starter/discussions
    about: Please use Discussions for Q&A and general support.
