name: "🧩 Task"
description: "A concrete, bounded piece of work (docs, scripts, CI, etc.)."
title: "task: <short title>"
labels: [task]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Tasks should be small, testable, and **agent-friendly**. Write acceptance criteria that a coding agent can verify.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Add docs deploy workflow and sync docs/ into website/docs"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope / changes
      description: "List files to touch, commands to run, and expected outputs/artifacts."
      placeholder: |
        - Create `.github/workflows/docs-deploy.yml`
        - Copy `docs/**` into `website/docs/` before build
        - Build Docusaurus; deploy to Pages
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Definition of Done (DoD)
      description: "Measurable, testable criteria."
      placeholder: |
        - CI workflow succeeds on `main`
        - Pages site publishes at <env URL>
        - All files under `docs/` visible in site nav
    validations:
      required: true
  - type: input
    id: estimate
    attributes:
      label: Estimate (optional)
      placeholder: "1h"
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [P0, P1, P2, P3]
      default: 1
  - type: textarea
    id: notes
    attributes:
      label: Notes / references
  - type: checkboxes
    id: agent
    attributes:
      label: Agent-ready checklist
      options:
        - label: File paths are explicit
          required: true
        - label: Commands are non-interactive
          required: true
        - label: DoD includes CI/evidence or a visible output
          required: true
