import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'architecture/architecture-quant-ai-strategy-design',
        {
          type: 'autogenerated',
          dirName: 'architecture/adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      collapsible: true,
      collapsed: true,
      items: ['adrs/readme'],
    },
    {
      type: 'category',
      label: 'Agents & Operations',
      collapsible: true,
      collapsed: false,
      items: ['agents', 'backtesting', 'deployment'],
    },
    {
      type: 'category',
      label: 'Capabilities',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'capabilities',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows',
        },
      ],
    },
    {
      type: 'category',
      label: 'Prompts',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'prompts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'research',
        },
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsible: true,
      collapsed: true,
      items: [
        'use_cases/use-cases-readme',
        'use_cases/use-cases-overview',
        'use-cases/insider_trading',
      ],
    },
    {
      type: 'category',
      label: 'Specifications',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'specs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Repository',
      collapsible: true,
      collapsed: true,
      items: ['sponsorship'],
    },
  ],
};

export default sidebars;
