import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'architecture/quant_ai_strategy_design',
        {
          type: 'autogenerated',
          dirName: 'architecture/adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Agents & Operations',
      collapsible: true,
      collapsed: false,
      items: ['agents', 'backtesting', 'deployment'],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsible: true,
      collapsed: true,
      items: ['use-cases-overview'],
    },
    {
      type: 'category',
      label: 'Specifications',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'specs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Repository',
      collapsible: true,
      collapsed: true,
      items: ['sponsorship'],
    },
  ],
};

export default sidebars;
