name: Validate Embeddings

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit-vector-dimensions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Audit vector dimensions
        run: python scripts/audit_vector_dims.py
