name: Validate Prefect Entrypoints

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  prefect-entrypoints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Validate Prefect deployments
        run: pytest tests/flows/test_entrypoints.py
