name: Codex Auto-Fix on Failure

on:
  workflow_run:
    workflows: ["CI"]      # <-- your main workflow name
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    env:
      FAILED_WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
      FAILED_RUN_URL: ${{ github.event.workflow_run.html_url }}
      FAILED_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      FAILED_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
    steps:
      - name: Verify OPENAI_API_KEY is present
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY is not set; skipping autofix." >&2
            exit 1
          fi

      - name: Checkout failing ref
        uses: actions/checkout@v4
        with:
          ref: ${{ env.FAILED_HEAD_SHA }}
          fetch-depth: 0

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          if [ -f package.json ]; then pnpm install --frozen-lockfile=false; fi

      - name: Run Codex (smallest possible fix)
        id: codex
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          sandbox: workspace-write
          safety-strategy: drop-sudo
          codex-args: '["--ask-for-approval","never"]'
          prompt: |
            You are working in a Node.js (pnpm) repo with Playwright/axe and CI gates.
            Goal: make CI pass with the smallest, safest change.
            Steps:
            1) Run the same commands CI runs.
            2) Identify the minimal edit to fix the failure.
            3) Apply ONLY that change (no refactors / no scope creep).
            4) Re-run the commands to confirm green.

            Commands to use:
            - pnpm build
            - pnpm test:smoke || true
            - pnpm test:a11y || true

            Output a brief summary in PLAN.md of what you changed and why.

      - name: Verify locally
        run: |
          pnpm build
          pnpm test:smoke || true
          pnpm test:a11y || true

      - name: Create PR with fix
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "fix(ci): minimal auto-fix via Codex"
          branch: codex/auto-fix-${{ github.event.workflow_run.run_id }}
          base: ${{ env.FAILED_HEAD_BRANCH }}
          title: "Auto-fix failing CI via Codex"
          body: |
            Codex generated this PR in response to a CI failure:
            - Workflow: `${{ env.FAILED_WORKFLOW_NAME }}`
            - Run: ${{ env.FAILED_RUN_URL }}

            See PLAN.md for summary of the minimal fix.
