name: monthly-template-refresh

on:
  schedule:
    - cron: "20 3 1 * *"   # 03:20 UTC on the 1st (adjust as you like)
  workflow_dispatch:
    inputs:
      overlay:
        description: "UI overlay (none | radix | shadcn | radix+shadcn)"
        required: false
        default: "none"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: monthly-template-refresh
  cancel-in-progress: false

jobs:
  build-fresh-template:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Dublin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Preinstall toolchain / deps Codex might need (network is easiest here).
      - name: Setup Node & Corepack (pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          # If the template needs any global setup, do it here.

      - name: Run Codex to (re)generate the template
        id: codex
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          sandbox: workspace-write         # allow writes, no network (we installed deps already)
          safety-strategy: drop-sudo       # least-privilege on GitHub-hosted runners
          prompt: |
            You are operating inside this repository’s workspace.
            Read and strictly follow docs/specs/AGENTS.md and docs/specs/SPEC.md.
            If present, also read docs/specs/DEVENV.md and docs/specs/UI-OVERLAYS.md.

            Task:
            - Bootstrap a fresh Next.js + Supabase starter aligned with TODAY'S create-next-app.
            - Apply all invariants and validations from the docs.
            - UI overlay: ${{ github.event.inputs.overlay || 'none' }}
            - Write a concise summary to PLAN.md:
              * CNA version detected today
              * Node version used
              * Packages added/removed and why
              * Validation results (build/smoke/a11y/doctor/i18n) with brief logs
              * Diffs from prior month that required adaptation

            Rules:
            - Work in repo ROOT (no extra subfolder).
            - Use pnpm and non-interactive commands in CI.
            - Prefer Supabase Publishable/Secret keys; backfill Anon/Service Role.
            - Make changes idempotent and safe for re-runs.
            - Do NOT fetch external templates; only use local docs/specs/*.

      - name: Stamp month for branch name
        id: when
        run: echo "yyyymm=$(date -u +'%Y-%m')" >> "$GITHUB_OUTPUT"

      - name: Create PR with results (review only; no merge expected)
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(template): monthly refresh ${ { steps.when.outputs.yyyymm } }"
          branch: "template/${{ steps.when.outputs.yyyymm }}"
          title: "Monthly template refresh – ${{ steps.when.outputs.yyyymm }}"
          body: |
            Automated monthly rebuild via Codex.

            Overlay: `${{ github.event.inputs.overlay || 'none' }}`
            Summary (from Codex): 
            ${{ steps.codex.outputs.final-message }}

            See PLAN.md for details. This PR is for review only; release will be cut from this branch.
          labels: |
            template
            automated
